name: Unit Testing

on:
  push:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:latest
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: password
          MYSQL_USERNAME: root
          MYSQL_DATABASE: test
    steps:
     - name: checkout the code
       uses: actions/checkout@v4

     - name: Setup PHP with pre-release PECL extension
       uses: shivammathur/setup-php@v2
       with:
         php-version: '8.3'
       
     - name: composer install
       run: |
         composer install
     - name: create environment 
       run: |
           cp .env.ci .env
          
           cp .env.ci  .env.testing

     - name: Check docker status
       run: |
        docker ps
      
     - name: Check the Network status
       run: |
        netstat -an | grep 3306

     - name: Wait for time to start the migration
       run: |
        sleep 15 

     - name: compilaction 
       run: |
         php artisan key:generate

     - name: dockernize the application
       run: |
         docker build -t hello-wops .
     - name: Login to DockerHub
       uses: docker/login-action@v1
       with:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_TOKEN}}
     - name: Tag image
       run: docker tag hello-wops ${{ secrets.DOCKERHUB_USERNAME }}/hello-wops
     - name: Push Docker image
       run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-wops
        
    

